name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Setup NDK
       uses: nttld/setup-ndk@v1
       with:
         ndk-version: r26d

     - name: Build .so
       run: ndk-build NDK_PROJECT_PATH=./src APP_BUILD_SCRIPT=./src/Android.mk NDK_APPLICATION_MK=./src/Application.mk

     - name: Upload Artifact
       uses: actions/upload-artifact@v3
       with:
         name: libASI
         path: libs/armeabi-v7a/*.so
